# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: subsurface
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
